import Link from 'next/link'

export default function({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <nav>
          <ul>
            <li><Link href="./other/1">Page 1</Link></li>
            <li><Link href="./other/2">Page 2</Link></li>
            <li><Link href="./other/3">Page 3</Link></li>
          </ul>
        </nav>

        <main>
          {children}
        </main>

		    <hr></hr>
        <footer>
          Footer!
        </footer>

      </body>
    </html>
  );
}
