import Link from 'next/link'

export default function({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <header>
          Header!
        </header>
        <nav>
          <ul>
            <li><Link href="./browser">Browser Component</Link></li>
            <li><Link href="./client">Client Component</Link></li>
            { [1,2,3].map((i) => 
            <li><Link href={`/other/${i}`}>RSC Child {i}</Link></li>
            )}
          </ul>
        </nav>

        <main>
          {children}
        </main>

		    <hr></hr>
        <footer>
          Footer!
        </footer>

      </body>
    </html>
  );
}
